"""Centralized checksum registry API for Rocq toolchain

This module provides a unified API for accessing tool checksums from JSON files,
following the exact pattern established by rules_wasm_component.
"""

def _load_tool_checksums_from_json(repository_ctx, tool_name):
    """Load checksums for a tool from JSON file
    
    This is the ONLY source of truth for tool checksums.
    JSON files are generated by the checksum_updater tool.
    
    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool (e.g., 'rocq')
        
    Returns:
        Dict: Tool data from JSON file
        
    Raises:
        fail: If JSON file not found
    """
    json_file = repository_ctx.path("@rules_rocq_rust//checksums/tools:{}.json".format(tool_name))
    if not json_file.exists:
        fail("Checksums not found: //checksums/tools/{}.json\n".format(tool_name) +
             "Run 'bazel run //tools/checksum_updater -- --tool={}' to generate.".format(tool_name))
    
    content = repository_ctx.read(json_file)
    return native.json.decode(content)

def get_tool_checksum(repository_ctx, tool_name, version, platform):
    """Get verified checksum from centralized registry
    
    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool (e.g., 'rocq')
        version: Version string (e.g., '2025.01.0')
        platform: Platform string (e.g., 'darwin_amd64', 'linux_amd64')
        
    Returns:
        String: SHA256 checksum, or None if not found
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)
    
    versions = tool_data.get("versions", {})
    version_data = versions.get(version, {})
    platforms = version_data.get("platforms", {})
    platform_data = platforms.get(platform, {})
    
    return platform_data.get("sha256")

def get_tool_info(repository_ctx, tool_name, version, platform):
    """Get complete tool information from centralized registry
    
    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool
        version: Version string
        platform: Platform string
        
    Returns:
        Dict: Complete platform information, or None if not found
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)
    
    versions = tool_data.get("versions", {})
    version_data = versions.get(version, {})
    platforms = version_data.get("platforms", {})
    
    return platforms.get(platform)

def get_latest_version(repository_ctx, tool_name):
    """Get latest available version for a tool
    
    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool
        
    Returns:
        String: Latest version, or None if tool not found
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)
    
    return tool_data.get("latest_version")

def list_supported_platforms(repository_ctx, tool_name, version):
    """List all supported platforms for a tool version
    
    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool
        version: Version string
        
    Returns:
        List: List of supported platform strings
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)
    
    versions = tool_data.get("versions", {})
    version_data = versions.get(version, {})
    platforms = version_data.get("platforms", {})
    
    return list(platforms.keys())