#!/usr/bin/env python3
"""
Create mock toolchain releases for testing download functionality.

This script creates mock toolchain archives that can be used to test
the download and extraction functionality without requiring real
Rocq Platform releases.
"""

import os
import sys
import tarfile
import zipfile
import hashlib
from io import BytesIO

def create_mock_toolchain(version="1.0.0", platform="darwin_arm64"):
    """Create a mock toolchain archive for testing."""
    
    # Create a temporary directory structure
    temp_dir = f"test-toolchain-{version}-{platform}"
    os.makedirs(temp_dir, exist_ok=True)
    
    # Create bin directory with mock tools
    bin_dir = os.path.join(temp_dir, "bin")
    os.makedirs(bin_dir, exist_ok=True)
    
    # Create mock binaries
    tools = ["test-tool", "test-compiler", "test-analyzer"]
    for tool in tools:
        tool_path = os.path.join(bin_dir, tool)
        if sys.platform == "win32":
            tool_path += ".exe"
        
        with open(tool_path, "w") as f:
            f.write(f"""#!/bin/bash
echo "Mock {tool} v{version} - Platform: {platform}"
echo "This is a test tool for toolchain functionality"
exit 0
""")
        
        os.chmod(tool_path, 0o755)
    
    # Create lib directory with mock libraries
    lib_dir = os.path.join(temp_dir, "lib")
    os.makedirs(lib_dir, exist_ok=True)
    
    libraries = ["stdlib.v", "prelude.v", "types.v"]
    for lib in libraries:
        lib_path = os.path.join(lib_dir, lib)
        with open(lib_path, "w") as f:
            f.write(f"""(** Mock library: {lib} *)
Definition mock_content : unit := tt.

(** Test definition for {lib} *)
Definition test_definition : nat := 42.

(** Test theorem for {lib} *)
Theorem test_theorem : forall (x: nat), x = x.
Proof.
  intros x. reflexivity.
Qed.
""")
    
    # Create archive based on platform
    if platform.startswith("darwin"):
        archive_name = f"test-toolchain-{version}-{platform}.tar.gz"
        create_tar_gz(temp_dir, archive_name)
    elif platform.startswith("linux"):
        archive_name = f"test-toolchain-{version}-{platform}.tar.gz"
        create_tar_gz(temp_dir, archive_name)
    elif platform.startswith("windows"):
        archive_name = f"test-toolchain-{version}-{platform}.zip"
        create_zip(temp_dir, archive_name)
    else:
        print(f"Unknown platform: {platform}")
        return None
    
    # Calculate checksum
    checksum = calculate_sha256(archive_name)
    
    # Clean up temporary directory
    import shutil
    shutil.rmtree(temp_dir)
    
    return archive_name, checksum

def create_tar_gz(source_dir, output_filename):
    """Create a tar.gz archive."""
    with tarfile.open(output_filename, "w:gz") as tar:
        tar.add(source_dir, arcname=os.path.basename(source_dir))

def create_zip(source_dir, output_filename):
    """Create a zip archive."""
    with zipfile.ZipFile(output_filename, "w", zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(source_dir):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, source_dir)
                zipf.write(file_path, arcname)

def calculate_sha256(filename):
    """Calculate SHA256 checksum of a file."""
    sha256_hash = hashlib.sha256()
    with open(filename, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

def main():
    """Main function to create test releases."""
    
    platforms = [
        "darwin_arm64",
        "darwin_amd64", 
        "linux_amd64",
        "windows_amd64"
    ]
    
    version = "1.0.0"
    
    print(f"Creating test toolchain releases v{version}...")
    
    releases_dir = "test_releases"
    os.makedirs(releases_dir, exist_ok=True)
    
    checksums = {}
    
    for platform in platforms:
        print(f"Creating release for {platform}...")
        archive_name, checksum = create_mock_toolchain(version, platform)
        
        if archive_name:
            # Move to releases directory
            dest_path = os.path.join(releases_dir, archive_name)
            os.rename(archive_name, dest_path)
            
            checksums[platform] = checksum
            print(f"  Created: {archive_name}")
            print(f"  Checksum: {checksum}")
    
    # Create checksums file
    checksums_file = os.path.join(releases_dir, f"checksums-v{version}.txt")
    with open(checksums_file, "w") as f:
        f.write(f"Test Toolchain v{version} Checksums\n")
        f.write(f"Generated by {os.path.basename(__file__)}\n\n")
        
        for platform, checksum in checksums.items():
            f.write(f"{platform}: {checksum}\n")
    
    print(f"\nCreated checksums file: {checksums_file}")
    print(f"\nAll test releases created in: {releases_dir}")
    print(f"\nTo use these for testing:")
    print(f"1. Start a local HTTP server: python3 -m http.server 8000")
    print(f"2. Update tool_registry.bzl to point to localhost:8000")
    print(f"3. Test the download functionality")

if __name__ == "__main__":
    main()