"""Repository rule: a hermetic Rust nightly `rules_rust` toolchain with rustc-dev.

Stage 2 of the rules_rust migration (see `docs/rules_rust-migration.md`).

This rule downloads a pinned Rust *nightly* sysroot -- including the
`rustc-dev` component -- from `static.rust-lang.org`, lays it out as a single
sysroot directory, and writes a `BUILD.bazel` exposing it as a `rules_rust`
`rust_toolchain` plus a `toolchain()` for registration.

Why a bespoke toolchain instead of `rules_rust`'s stock `rust` extension:
rocq-of-rust's `rocq-of-rust-rustc` is a `rustc` *driver* built under
`#![feature(rustc_private)]`; it `extern crate rustc_driver` and friends. Those
`rustc_*` crates only ship in the `rustc-dev` component, which the stock
extension does not download. `download_rust_nightly` copies the `rustc-dev`
rlibs/.so into `lib/rustlib/<triple>/lib/` -- the same directory the
`rust_stdlib_filegroup` globs -- so the toolchain's `rust_std` automatically
carries them and `extern crate rustc_driver` resolves from the sysroot.

The filegroup / `rust_toolchain` shape is modelled on rules_rust 0.70.0's own
`rust/private/repository_utils.bzl` (`BUILD_for_compiler`, `BUILD_for_stdlib`,
`BUILD_for_cargo`, `_build_file_for_rust_toolchain_template`).
"""

load(
    "//coq_of_rust/private:rust_nightly.bzl",
    "DEFAULT_NIGHTLY",
    "detect_rust_platform",
    "download_rust_nightly",
)

# Per-`rules_rust`-"system" extension + stdlib link flags, taken verbatim from
# rules_rust 0.70.0 `rust/platform/triple_mappings.bzl`.
_SYSTEM_INFO = {
    "darwin": {
        "binary_ext": "",
        "dylib_ext": ".dylib",
        "staticlib_ext": ".a",
        "stdlib_linkflags": ["-lSystem", "-lresolv"],
    },
    "linux": {
        "binary_ext": "",
        "dylib_ext": ".so",
        "staticlib_ext": ".a",
        "stdlib_linkflags": ["-ldl", "-lpthread"],
    },
}

# Bazel platform constraints for each supported triple, so the generated
# `toolchain()` only resolves on a matching host.
_PLATFORM_CONSTRAINTS = {
    "aarch64-apple-darwin": [
        "@platforms//os:macos",
        "@platforms//cpu:aarch64",
    ],
    "x86_64-apple-darwin": [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
    "x86_64-unknown-linux-gnu": [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    "aarch64-unknown-linux-gnu": [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
    ],
}

# Map a Rust target triple to the rules_rust "system" key above.
def _system_for_triple(triple):
    if "apple-darwin" in triple:
        return "darwin"
    if "linux" in triple:
        return "linux"
    fail("Unsupported Rust target triple for hermetic toolchain: {}".format(triple))

def _starlark_str_list(items):
    return "[" + ", ".join(['"{}"'.format(i) for i in items]) + "]"

def _rust_toolchain_repo_impl(repository_ctx):
    rust_nightly = repository_ctx.attr.rust_nightly
    triple = detect_rust_platform(repository_ctx)
    if not triple:
        fail(
            "rust_toolchain_repo: unsupported host platform {}/{}. ".format(
                repository_ctx.os.name,
                repository_ctx.os.arch,
            ) + "Add it to RUST_PLATFORM_MAP in rust_nightly.bzl.",
        )

    system = _system_for_triple(triple)
    info = _SYSTEM_INFO[system]

    # Download nightly + rustc-dev into `sysroot/`. download_rust_nightly copies
    # the rustc-dev rlibs/.so into sysroot/lib/rustlib/<triple>/lib/.
    repository_ctx.report_progress(
        "Downloading hermetic Rust {} (+rustc-dev) for {}".format(rust_nightly, triple),
    )
    download_rust_nightly(repository_ctx, rust_nightly, triple, output = "sysroot")

    if not repository_ctx.path("sysroot/bin/rustc").exists:
        fail("rust_toolchain_repo: hermetic Rust download failed (no sysroot/bin/rustc).")

    # iso_date / version for the rust_toolchain (nightly => version "nightly").
    iso_date = rust_nightly.replace("nightly-", "")

    binary_ext = info["binary_ext"]
    dylib_ext = info["dylib_ext"]
    staticlib_ext = info["staticlib_ext"]

    # --- filegroups -----------------------------------------------------------
    #
    # Modelled on rules_rust's BUILD_for_compiler / BUILD_for_stdlib /
    # BUILD_for_cargo. The crucial difference from the stock toolchain: the
    # `rust_std` filegroup globs `lib/rustlib/<triple>/lib/` which -- because
    # download_rust_nightly merged rustc-dev there -- now also contains the
    # `librustc_*` rlibs and `.so`s needed for `rustc_private`.
    build_content = '''# Generated by rules_rocq_rust -- hermetic Rust nightly + rustc-dev toolchain.
# Stage 2 of the rules_rust migration; see docs/rules_rust-migration.md.
# DO NOT EDIT: produced by coq_of_rust/private/rust_toolchain_repo.bzl.

load("@rules_rust//rust:toolchain.bzl", "rust_stdlib_filegroup", "rust_toolchain")

package(default_visibility = ["//visibility:public"])

# --- compiler -----------------------------------------------------------------

filegroup(
    name = "rustc",
    srcs = ["sysroot/bin/rustc{binary_ext}"],
)

filegroup(
    name = "rustdoc",
    srcs = ["sysroot/bin/rustdoc{binary_ext}"],
)

# rustc_lib: shared libs rustc itself dlopen()s / links against -- libLLVM-*,
# librustc_driver-*, codegen backends. `sysroot/lib` carries libLLVM and the
# `libLLVM-19-rust-1.85.0-nightly{dylib_ext}` symlink.
filegroup(
    name = "rustc_lib",
    srcs = glob(
        [
            "sysroot/bin/*{dylib_ext}",
            "sysroot/lib/*{dylib_ext}*",
            "sysroot/lib/rustlib/{triple}/codegen-backends/*{dylib_ext}",
            "sysroot/lib/rustlib/{triple}/lib/*{dylib_ext}*",
            "sysroot/lib/rustlib/{triple}/lib/*.rmeta",
        ],
        allow_empty = True,
    ),
)

# --- cargo --------------------------------------------------------------------

filegroup(
    name = "cargo",
    srcs = ["sysroot/bin/cargo{binary_ext}"],
)

# --- standard library + rustc-dev crates -------------------------------------
#
# This filegroup MUST include the rustc-dev crates (librustc_*) so that a
# rustc_private driver can resolve `extern crate rustc_driver` from the
# sysroot. download_rust_nightly copies rustc-dev into the same
# lib/rustlib/<triple>/lib/ directory globbed here, so they are picked up
# alongside the ordinary std rlibs.
rust_stdlib_filegroup(
    name = "rust_std-{triple}",
    srcs = glob(
        [
            "sysroot/lib/rustlib/{triple}/lib/*.rlib",
            "sysroot/lib/rustlib/{triple}/lib/*.rmeta",
            "sysroot/lib/rustlib/{triple}/lib/*{dylib_ext}*",
            "sysroot/lib/rustlib/{triple}/lib/*{staticlib_ext}",
            "sysroot/lib/rustlib/{triple}/lib/self-contained/**",
        ],
        allow_empty = True,
    ),
)

# --- toolchain ----------------------------------------------------------------

rust_toolchain(
    name = "rust_nightly_impl",
    binary_ext = "{binary_ext}",
    cargo = ":cargo",
    channel = "nightly",
    default_edition = "2021",
    dylib_ext = "{dylib_ext}",
    exec_triple = "{triple}",
    iso_date = "{iso_date}",
    rust_doc = ":rustdoc",
    rust_std = ":rust_std-{triple}",
    rustc = ":rustc",
    rustc_lib = ":rustc_lib",
    staticlib_ext = "{staticlib_ext}",
    stdlib_linkflags = {stdlib_linkflags},
    target_triple = "{triple}",
    version = "nightly",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "rust_nightly",
    exec_compatible_with = {compat},
    target_compatible_with = {compat},
    toolchain = ":rust_nightly_impl",
    toolchain_type = "@rules_rust//rust:toolchain_type",
)
'''.format(
        binary_ext = binary_ext,
        dylib_ext = dylib_ext,
        staticlib_ext = staticlib_ext,
        triple = triple,
        iso_date = iso_date,
        stdlib_linkflags = _starlark_str_list(info["stdlib_linkflags"]),
        compat = _starlark_str_list(_PLATFORM_CONSTRAINTS[triple]),
    )

    repository_ctx.file("BUILD.bazel", build_content)

rust_toolchain_repo = repository_rule(
    implementation = _rust_toolchain_repo_impl,
    attrs = {
        "rust_nightly": attr.string(
            default = DEFAULT_NIGHTLY,
            doc = "Rust nightly version, e.g. 'nightly-2024-12-07'.",
        ),
    },
    doc = "Downloads a hermetic Rust nightly sysroot (incl. rustc-dev) and " +
          "exposes it as a rules_rust rust_toolchain. See " +
          "docs/rules_rust-migration.md (Stage 2).",
)
